name: CI
on:
  pull_request:
  push:
    branches: ["*"]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install
        run: npm i --no-audit --no-fund
      - name: Ensure package scripts
        run: node ops/ensure-package.mjs
      - name: Lint & Smoke
        run: npm run ci:verify
